package main;

import entity.Demon;
import entity.SKELETON;
import object.obj_chest;
import object.obj_pot;
import object.obj_torch;

public class AssetSetter {
    GamePanel gp;
    public AssetSetter(GamePanel gp)
    {
        this.gp = gp;
    }

    public void setObject()
    {
        int mapNum=0;
        gp.obj[mapNum][0] = new obj_chest(gp);
        gp.obj[mapNum][0].worldX = 22 * gp.tileSize;
        gp.obj[mapNum][0].worldY = 1 * gp.tileSize;
        gp.obj[mapNum][0] = new obj_pot(gp);
        gp.obj[mapNum][0].worldX = 22 * gp.tileSize;
        gp.obj[mapNum][0].worldY = 1 * gp.tileSize;
        gp.obj[mapNum][0] = new obj_torch(gp);
        gp.obj[mapNum][0].worldX = 22 * gp.tileSize;
        gp.obj[mapNum][0].worldY = 1 * gp.tileSize;


    }
    public void setMonster()
    {
        int mapNum=0;
        int i=0;
        //MAP 1
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 32 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 17 * gp.tileSize ;//1
        i++;
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 12 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 17 * gp.tileSize ;//2
        i++;
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 13 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 33 * gp.tileSize ;//3
        i++;
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 22 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 32 * gp.tileSize ;//4
        i++;
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 31 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 34 * gp.tileSize ;//5
        i++;
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 38 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 27 * gp.tileSize ;//6
        i++;
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 18 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 27 * gp.tileSize ;//7
        i++;
        gp.Monsters[mapNum][i] = new SKELETON(gp);
        gp.Monsters[mapNum][i].worldX = 14 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 16 * gp.tileSize ;//8
        i++;
        //DEMONS
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 33 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 23 * gp.tileSize ;//9
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 33 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 23 * gp.tileSize ;//10
        i++;


        //MAP 2
        mapNum ++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 5 * gp.tileSize ;
        i++;

        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 10 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 14 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 14 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 14 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 14 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 14 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 14 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 14 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 14 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 4 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 19 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 4 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 19 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 4 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 19 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 4 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 19 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 46 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 9 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 46 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 9 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 46 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 9 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 46 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 9 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 46 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 9 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 3 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 3 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 16 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 16 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 16 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 40 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 42 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 40 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 42 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 40 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 42 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 40 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 42 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 40 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 42 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 40 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 42 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 40 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 42 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 37 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 37 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 37 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 37 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 28 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 17 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 28 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 17 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 28 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 17 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 33 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 33 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 33 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 15 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;

        //MAP 3
        mapNum++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 7 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 7 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 18 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 2 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 18 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 25 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 25 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 19 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 12 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 19 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 12 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 19 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 12 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 10 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 15 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 19 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 4 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 19 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 4 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 5 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 37 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 20 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 34 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 21 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 47 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 44 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 44 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 44 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 28 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;
        i++;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;
        //Boss lvl 3
        gp.Monsters[mapNum][i] = new Demon(gp);
        gp.Monsters[mapNum][i].worldX = 41 * gp.tileSize ;
        gp.Monsters[mapNum][i].worldY = 13 * gp.tileSize ;

    }
}
